/* eslint-disable */
// @ts-nocheck
// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeProRouteImport } from './routes/welcome-pro'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientTokenRouteImport } from './routes/client.$token'
import { Route as ClientReportIdRouteImport } from './routes/client-report.$id'
import { Route as PlannerIndexRouteImport } from './routes/planner.index'
import { Route as PlannerIdRouteImport } from './routes/planner.$id'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks.stripe'

const WelcomeProRoute = WelcomeProRouteImport.update({ id: '/welcome-pro', path: '/welcome-pro', getParentRoute: () => rootRouteImport } as any)
const TermsRoute = TermsRouteImport.update({ id: '/terms', path: '/terms', getParentRoute: () => rootRouteImport } as any)
const SettingsRoute = SettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => rootRouteImport } as any)
const PrivacyRoute = PrivacyRouteImport.update({ id: '/privacy', path: '/privacy', getParentRoute: () => rootRouteImport } as any)
const MessagesRoute = MessagesRouteImport.update({ id: '/messages', path: '/messages', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const InspirationRoute = InspirationRouteImport.update({ id: '/inspiration', path: '/inspiration', getParentRoute: () => rootRouteImport } as any)
const DashboardRoute = DashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => rootRouteImport } as any)
const CheckEmailRoute = CheckEmailRouteImport.update({ id: '/check-email', path: '/check-email', getParentRoute: () => rootRouteImport } as any)
const CalendarRoute = CalendarRouteImport.update({ id: '/calendar', path: '/calendar', getParentRoute: () => rootRouteImport } as any)
const BillingRoute = BillingRouteImport.update({ id: '/billing', path: '/billing', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const ClientTokenRoute = ClientTokenRouteImport.update({ id: '/client/$token', path: '/client/$token', getParentRoute: () => rootRouteImport } as any)
const ClientReportIdRoute = ClientReportIdRouteImport.update({ id: '/client-report/$id', path: '/client-report/$id', getParentRoute: () => rootRouteImport } as any)
const PlannerIndexRoute = PlannerIndexRouteImport.update({ id: '/planner/', path: '/planner/', getParentRoute: () => rootRouteImport } as any)
const PlannerIdRoute = PlannerIdRouteImport.update({ id: '/planner/$id', path: '/planner/$id', getParentRoute: () => rootRouteImport } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({ id: '/api/public/webhooks/stripe', path: '/api/public/webhooks/stripe', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/calendar': typeof CalendarRoute
  '/check-email': typeof CheckEmailRoute
  '/dashboard': typeof DashboardRoute
  '/inspiration': typeof InspirationRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/welcome-pro': typeof WelcomeProRoute
  '/client/$token': typeof ClientTokenRoute
  '/client-report/$id': typeof ClientReportIdRoute
  '/planner/$id': typeof PlannerIdRoute
  '/planner/': typeof PlannerIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/calendar': typeof CalendarRoute
  '/check-email': typeof CheckEmailRoute
  '/dashboard': typeof DashboardRoute
  '/inspiration': typeof InspirationRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/welcome-pro': typeof WelcomeProRoute
  '/client/$token': typeof ClientTokenRoute
  '/client-report/$id': typeof ClientReportIdRoute
  '/planner/$id': typeof PlannerIdRoute
  '/planner': typeof PlannerIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/calendar': typeof CalendarRoute
  '/check-email': typeof CheckEmailRoute
  '/dashboard': typeof DashboardRoute
  '/inspiration': typeof InspirationRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/welcome-pro': typeof WelcomeProRoute
  '/client/$token': typeof ClientTokenRoute
  '/client-report/$id': typeof ClientReportIdRoute
  '/planner/$id': typeof PlannerIdRoute
  '/planner/': typeof PlannerIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/billing' | '/calendar' | '/check-email' | '/dashboard' | '/inspiration' | '/login' | '/messages' | '/privacy' | '/settings' | '/terms' | '/welcome-pro' | '/client/$token' | '/client-report/$id' | '/planner/$id' | '/planner/' | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/billing' | '/calendar' | '/check-email' | '/dashboard' | '/inspiration' | '/login' | '/messages' | '/privacy' | '/settings' | '/terms' | '/welcome-pro' | '/client/$token' | '/client-report/$id' | '/planner/$id' | '/planner' | '/api/public/webhooks/stripe'
  id: '__root__' | '/' | '/billing' | '/calendar' | '/check-email' | '/dashboard' | '/inspiration' | '/login' | '/messages' | '/privacy' | '/settings' | '/terms' | '/welcome-pro' | '/client/$token' | '/client-report/$id' | '/planner/$id' | '/planner/' | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  CalendarRoute: typeof CalendarRoute
  CheckEmailRoute: typeof CheckEmailRoute
  DashboardRoute: typeof DashboardRoute
  InspirationRoute: typeof InspirationRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  WelcomeProRoute: typeof WelcomeProRoute
  ClientTokenRoute: typeof ClientTokenRoute
  ClientReportIdRoute: typeof ClientReportIdRoute
  PlannerIdRoute: typeof PlannerIdRoute
  PlannerIndexRoute: typeof PlannerIndexRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  BillingRoute,
  CalendarRoute,
  CheckEmailRoute,
  DashboardRoute,
  InspirationRoute,
  LoginRoute,
  MessagesRoute,
  PrivacyRoute,
  SettingsRoute,
  TermsRoute,
  WelcomeProRoute,
  ClientTokenRoute,
  ClientReportIdRoute,
  PlannerIdRoute,
  PlannerIndexRoute,
  ApiPublicWebhooksStripeRoute,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addRouteTypes()
