/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeProRouteImport } from './routes/welcome-pro'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientReportIdRouteImport } from './routes/client-report.$id'
import { Route as PlannerIndexRouteImport } from './routes/planner.index'
import { Route as PlannerIdRouteImport } from './routes/planner.$id'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks.stripe'

const WelcomeProRoute = WelcomeProRouteImport.update({
  id: '/welcome-pro',
  path: '/welcome-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientReportIdRoute = ClientReportIdRouteImport.update({
  id: '/client-report/$id',
  path: '/client-report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerIndexRoute = PlannerIndexRouteImport.update({
  id: '/planner/',
  path: '/planner/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerIdRoute = PlannerIdRouteImport.update({
  id: '/planner/$id',
  path: '/planner/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/calendar': typeof CalendarRoute
  '/check-email': typeof CheckEmailRoute
  '/client-report/$id': typeof ClientReportIdRoute
  '/dashboard': typeof DashboardRoute
  '/inspiration': typeof InspirationRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/welcome-pro': typeof WelcomeProRoute
  '/planner/$id': typeof PlannerIdRoute
  '/planner/': typeof PlannerIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/calendar': typeof CalendarRoute
  '/check-email': typeof CheckEmailRoute
  '/client-report/$id': typeof ClientReportIdRoute
  '/dashboard': typeof DashboardRoute
  '/inspiration': typeof InspirationRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/welcome-pro': typeof WelcomeProRoute
  '/planner/$id': typeof PlannerIdRoute
  '/planner': typeof PlannerIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/calendar': typeof CalendarRoute
  '/check-email': typeof CheckEmailRoute
  '/client-report/$id': typeof ClientReportIdRoute
  '/dashboard': typeof DashboardRoute
  '/inspiration': typeof InspirationRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/welcome-pro': typeof WelcomeProRoute
  '/planner/$id': typeof PlannerIdRoute
  '/planner/': typeof PlannerIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/calendar'
    | '/check-email'
    | '/client-report/$id'
    | '/dashboard'
    | '/inspiration'
    | '/login'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/welcome-pro'
    | '/planner/$id'
    | '/planner/'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/calendar'
    | '/check-email'
    | '/client-report/$id'
    | '/dashboard'
    | '/inspiration'
    | '/login'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/welcome-pro'
    | '/planner/$id'
    | '/planner'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/calendar'
    | '/check-email'
    | '/client-report/$id'
    | '/dashboard'
    | '/inspiration'
    | '/login'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/welcome-pro'
    | '/planner/$id'
    | '/planner/'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  CalendarRoute: typeof CalendarRoute
  CheckEmailRoute: typeof CheckEmailRoute
  ClientReportIdRoute: typeof ClientReportIdRoute
  DashboardRoute: typeof DashboardRoute
  InspirationRoute: typeof InspirationRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  WelcomeProRoute: typeof WelcomeProRoute
  PlannerIdRoute: typeof PlannerIdRoute
  PlannerIndexRoute: typeof PlannerIndexRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome-pro': {
      id: '/welcome-pro'
      path: '/welcome-pro'
      fullPath: '/welcome-pro'
      preLoaderRoute: typeof WelcomeProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-report/$id': {
      id: '/client-report/$id'
      path: '/client-report/$id'
      fullPath: '/client-report/$id'
      preLoaderRoute: typeof ClientReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/': {
      id: '/planner/'
      path: '/planner'
      fullPath: '/planner/'
      preLoaderRoute: typeof PlannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/$id': {
      id: '/planner/$id'
      path: '/planner/$id'
      fullPath: '/planner/$id'
      preLoaderRoute: typeof PlannerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  CalendarRoute: CalendarRoute,
  CheckEmailRoute: CheckEmailRoute,
  ClientReportIdRoute: ClientReportIdRoute,
  DashboardRoute: DashboardRoute,
  InspirationRoute: InspirationRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  WelcomeProRoute: WelcomeProRoute,
  PlannerIdRoute: PlannerIdRoute,
  PlannerIndexRoute: PlannerIndexRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
